# Generated by Django 4.1.5 on 2023-01-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_data1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="import_data1",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
