# Generated by Django 4.1.6 on 2023-03-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("import_data1", "0002_alter_import_data1_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="import_data1", name="description",),
        migrations.RemoveField(model_name="import_data1", name="price",),
        migrations.RemoveField(model_name="import_data1", name="summary",),
        migrations.RemoveField(model_name="import_data1", name="title",),
    ]
