# Generated by Django 4.1.6 on 2023-03-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_remove_uploded_files_diploma_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="upload_files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="uploded_files",),
    ]
